version: 2

sources:
  - name: raw_data_circle
    description: raw data circle sportsweart from LW
    tables:
      - name: raw_cc_stock
        description: stock of products
      - name: raw_cc_sales
        description: sales of products
        tests:
          - unique:
              column_name:  "(product_id || '_' || date_date)"